<head>
       <meta charset="utf-8">
       <?php echo $this->headTitle('SIMOB '. $this->translate('Sistema Imobiliaria'))->setSeparator(' - ')->setAutoEscape(false) ?>

       <?php echo $this->headMeta()
           ->appendName('viewport', 'width=device-width, initial-scale=1.0')
           ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
       ?>

       <!-- Le styles -->
       <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                       ->prependStylesheet($this->basePath() . '/css/site.css')
                       ->prependStylesheet($this->basePath() . '/css/notifIt.css')
                       ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.4.custom.min.css');
         ?>
       <!-- Scripts -->
       <?php echo $this->headScript()
           ->prependFile($this->basePath() . '/js/simob/default.js')         
           ->prependFile($this->basePath() . '/js/bootstrap.js');
       ?>
       <?php echo $this->inlineScript()//adiciona o javascript ?>
</head>
<body>
    <header id="cabecalho"><img></header>
        <div id="cssmenu">
            <ul>
                <li class='active'><a href='<?php echo $this->url('front_end') ?>'><span>Home</span></a></li>
                <li><a href='#'><span>Imoveis</span></a></li>
                <li><a href='#'><span>Lançamentos</span></a></li>
                <li><a href='<?php echo $this->url('login_admin')?>'><span>Login</span></a></li>
                <li class='last'><a href='#'><span>Contato</span></a></li>
             </ul>
        </div>
         <aside>
            <div>
                <header>Simulação de financiamento</header>
                <ul>
                    <li><a href="https://www.itau.com.br/creditos-financiamentos/imoveis/simulador/" target="blank"><img src= <?php echo $this->basePath()?>"/img/logos/itau.jpg"></a></li>
                    <li><a href="https://wwws3.hsbc.com.br/HPB-CHM-SIMULADOR/servlets/HPBCreditoImobiliarioServlet" target="blank"><img src=<?php echo $this->basePath()?>"/img/logos/hsbc.jpg"></a></li>
                    <li><a href="http://www.bradesco.com.br/html/classic/produtos-servicos/emprestimo-e-financiamento/index.shtm?par=1" target="blank"><img src=<?php echo $this->basePath()?>"/img/logos/bradesco.jpg"></a></li>
                    <li><a href="http://www8.caixa.gov.br/siopiinternet/simulaOperacaoInternet.do?method=inicializarCasoUso" target="blank"><img src=<?php echo $this->basePath()?>"/img/logos/caixa.jpg"></a></li>
                    <li><a href="http://www.bb.com.br/portalbb/home24,116,2117,1,1,1,1.bb?codigoMenu=172" target="blank"><img src=<?php echo $this->basePath()?>"/img/logos/bb.jpg"></a></li>
                </ul>
            </div>
        </aside>
        <div class="container">
           <?php echo $this->content; ?>
        </div>
        <footer id="rodape">
            <div class="esquerda grand">logo</div>
            <div class="central"><!--http://www.peninsulabuzios.com.br/--></div>
            <div class="esquerda">lista com bairros de buzios</div>
        </footer>
</body>