<html>
        <?php
        $form = $this->busca;
        $form->setAttribute('action', $this->url($this->rota));
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form),
        $this->formCollection($form),
        $this->form()->closeTag();

    ?>
</html>
<div id="dialog-busca" title="selecão de cidade" style="display: none;">
    <section>
        <label>UF</label>
        <select class="uf-select">
            <?php foreach($listaEstados as $row){
                    if($row['selected']){
                        echo '<option value="'.$row['value'].'" selected ="selected" disabled = "disabled">'.$row['label'].'</option>';
                    }else{
                        echo '<option value="'.$row['value'].'">'.$row['label'].'</option>';
                    }
                }
                ?>   
        </select>
        <label>Cidade</label>
        <select class="cidade-select">
            <option>selecione um estado</option>
        </select>
    </section>
</div>
