<html>
        <?php
        $form = $this->busca;
        $form->setAttribute('action', $this->url($this->rota));
        $form->setAttribute('method', 'post');
        echo $this->form()->openTag($form),
        $this->formCollection($form),
        $this->form()->closeTag();

    ?>
</html>
<div id="dialog-busca" title="selecão de cidade" style="display: none;">
    
    <p>
        <label>UF</label>
        <select id="uf-select">
            <?php foreach($listaEstados as $row):?>
                <option><?php echo $row; ?></option>
            <?php endforeach;?>
        </select>
        <label>Cidade</label>
        <select id="cidade-select">
            <option>selecione um estado</option>
        </select>
    </p>
</div>
