    <tbody>
    <?php foreach($comodos as $comodo):?>
    <tr>
    <input type="hidden" class="id-comodo" value="<?php echo $comodo->getId();?>">
        <td class="descricao">
            <?php echo $comodo->getDescricao();?>
        </td>
        <td>
            <button class="alterar">Alterar</button>
            <button class="deletar">Deletar</button>
        </td>
    </tr>
    <?php endforeach;?>
    </tbody>