    <tbody>       
    <?php foreach($this->comodos as $comodo):?>
            <tr>
            <input type="hidden" class="id-comodo" value="<?php echo $comodo->getId();?>">
                <td class="descricao">
                    <?php echo $comodo->getDescricao();?>
                </td>
                <td>
                    <button class="alterar-comodo update-default">Alterar</button>
                    <button class="deletar-comodo delete-default">Deletar</button>
                </td>
            </tr>
    <?php endforeach;?>
    </tbody>