<header>
    Gerenciamento de Bairros
</header>
<section class="buscar">
    <?php echo $this->partialBusca; ?>
</section>
<section class="listar">
    <h4>Bairros Cadastrados</h4>
    <?php if($this->haDados):?>
                <table id="tabela-bairros" class="default-table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Cidade</th>
                            <th>Estado</th>
                            <th>Alterar</th>
                            <th>Deletar</th>
                        </tr>
                    </thead>
                    <?php echo $this->partialListarBairros; ?>
                 </table>
                    <?php echo $this->paginacao; ?>
    <?php else:?>
        <h1>Nenhum registro encontrado</h1>
    <?php endif;?>
</section>
<div id="dialog-mensagem" title="Aviso" style="display: none;">
    
    <p id="mensagem">
        
    </p>
</div>
<?php

?>