<div id="barra-paginacao">
        <?php if($this->paginacao['ha_anterior'] == true):?>
           <a href="#" class="pagina-anterior" url="<?php echo $this->url($this->rota.'/paginaAnterior');?>"  data-anterior = "<?php echo $this->paginacao['pagina_anterior'] ?>"><img src="/img/anterior.png"></a>
        <?php endif;?>

        <?php if($this->paginacao['ha_proxima'] == true):?>
           <a href="#"  class="proxima-pagina" url="<?php echo $this->url($this->rota.'/proximaPagina');?>" data-proxima = "<?php echo $this->paginacao['proxima_pagina'] ?>"><img src="/img/proximo.png"></a>
        <?php endif;?>
</div>