<div id="barra-paginacao">
        <?php if(boolval($this->paginacao['ha_anterior'])==true):?>
           <a href="#" class="pagina-anterior" url="<?php echo $this->url($this->rota.'/paginaAnterior');?>"  data-anterior = "<?php echo $this->paginacao['pagina_anterior'] ?>">anterior</a>
        <?php endif;?>

        <?php if(boolval($this->paginacao['ha_proxima'])==true):?>
           <a href="#"  class="proxima-pagina" url="<?php echo $this->url($this->rota.'/proximaPagina');?>" data-proxima = "<?php echo $this->paginacao['proxima_pagina'] ?>">proximo</a>
        <?php endif;?>
</div>