<header>
    Gerenciamento de Proprietarios
</header>
<section class="buscar">
   <?php echo $this->busca; ?>
</section>
<section class="listar">
    <h4>Proprietarios Cadastrados</h4>
    <?php if($this->haDados):?>
                <table id="tabela-proprietarios" class="default-table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Cpf</th>
                            <th>Edicao</th>
                        </tr>
                    </thead>
                    <?php echo $this->tableList; ?>
                 </table>
                 <?php echo $this->paginacao; ?>
    <?php else:?>
        <h1>Nenhum registro encontrado</h1>
    <?php endif;?>
</section>
<div id="dialog-mensagem" title="Aviso" style="display: none;">
    <p id="mensagem"></p>
</div>