<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
            <link type="text/css" href="/css/galeria/right.css" rel="stylesheet" />
            <script type="text/javascript" src="/js/galeria/jquery.js"></script>
            <script type="text/javascript" src="/js/galeria/jquery.jcarousel.min.js"></script>
            <script type="text/javascript" src="/js/galeria/jquery.pikachoose.min.js"></script>
            <script type="text/javascript" src="/js/galeria/jquery.touchwipe.min.js"></script>
            <script language="javascript">
            $(document).ready(
		function (){
			$("#pikame").PikaChoose({carousel:true, carouselVertical:true});
			});
	    </script>

		
</head>
    <body>
            
        
        
            <div class="pikachoose">
            <ul id="pikame" class="jcarousel-skin-pika">
                    <?php foreach($midias as $row):?>
                        <?php
                        if($row->getTipo()!= \Application\Entity\TipoMidia::SEM_MIDIA){
                        ?>
                            <li><a href="#"><image src="<?php echo $row->getUrl(); ?>"></a><span></span></li>
                        <?php
                        }
                        ?>
                    <?php endforeach; ?>  
            </ul>
            </div>
        
            <div class="contatenos">
                <div>Gostou? Contate-nos.</div>
                <img src="/img/email.png">
                <img src="/img/facebook.png">
                <img src="/img/twitter.png">
            </div>
        
            <div>
                <ul class="informacoes">
                    <?php
                        echo '<li class="destaque">'.$imovel->mascaraValorTransacao().'</li>';
                        echo '<li>Cidade: '.$imovel->getBairro()->getCidade()->getNome().'</li>';
                        echo '<li>Bairro: '.$imovel->getBairro()->getNome().'</li>';
                        echo '<li>Rua: '.$imovel->getRua().'</li>';
                        echo '<li>Area total: '.$imovel->getAreaTotal().'</li>';
                        echo '<li>Area Construída: '.$imovel->getAreaConstruida().'</li>';
                    ?>
                </ul>
                
                <?php echo '<div class="desc"><div>Descrição</div>'.$imovel->getDescricao().'</div>';?>
                
                <ul class="comodos">
                    <label>Comodos</label>
                    <?php 
                        foreach ($comodos as $row){
                            echo "<li>".$row->getTipoComodo()->getDescricao().": ".$row->getQtd()."</li>";
                        }
                    ?>
                </ul>
            </div>
    </body>
</html>
