<header>
    Gerenciamento de Bairros
</header>
<section class="buscar">
    buscar
</section>
<section class="listar">
    <h4>Bairros Cadastrados</h4>
    <table id="tabela-bairros" border='1px'>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Alterar</th>
                <th>Deletar</th>
            </tr>              
        </thead>
        <?php echo $this->partialListarBairros; ?>
     </table>
        <?php echo $this->paginacao; ?>
</section>
<?php

?>