<header>
    Passo 3
</header>
<section class="criar">
       <?php if(empty($midiasSalvas)): ?><!-- sem nenhuma imagem salva-->
        <div id="preview" display="show">
            <h3>Nenhuma Imagem</h3>
            <div id="capa" display="none" background="none">
                Arraste uma imagem para capa do álbum.
            </div>
            <ul>
            </ul>
            <div id="lixeira" display="none">
            </div>
        </div>
       <?php else:?>   <!-- com imagens na galeria-->         
        <div id="preview" display="none">
                 <?php 
                    $capa = null;
                    if(is_array($midiasSalvas)){
                        foreach($midiasSalvas as $row){
                            if($row->getCapa()==TRUE){
                                $capa = $row;
                            }
                        }
                    }else{
                            $capa = $midiasSalvas;
                    }
                  ?>
                <?php if(is_null($capa)):?>
                        <div id="capa" background="show"><!--exibe a imagem de background com a imagem foto_de_capa.png-->
                            Arraste uma imagem para capa do álbum.
                        </div>
                 <?php else:?>           
                        <div id="capa">
                            <img src="<?php echo $capa->getUrl();?>">
                            <rodape>Foto de capa</rodape>
                        </div>
                 <?php endif;?>
            
             <ul> 
                 <?php
                    if(is_array($midiasSalvas)){
                        foreach ($midiasSalvas as $row){
                            if($row->getTipo()!= \Application\Entity\TipoMidia::SEM_MIDIA){
                                echo '<li class="miniatura"><img src="'.$row->getUrl().'"><input type="hidden" value="'.$row->getId().'"><input type="text" class="nome-miniatura" placeholder="nomear Imagem" nome="'.$row->getNome().'" value="'.$row->getNome().'"></li>';
                            }
                         }
                    }else{
                        if($midiasSalvas->getTipo()!= \Application\Entity\TipoMidia::SEM_MIDIA){
                            echo '<li class="miniatura"><img src="'.$midiasSalvas->getUrl().'"><input type="hidden" value="'.$midiasSalvas->getId().'"><input class="nome-miniatura" type="text" placeholder="nomear Imagem" nome="'.$midiasSalvas->getNome().'" value="'.$midiasSalvas->getNome().'"></li>';
                        }
                    }
                    
                 ?>
             </ul>
             <div id="lixeira" display="show">
             </div>
        </div>    
       <?php endif;?>       
    <?php
    $form = $this->partialCadastro3;
    $form->setAttribute('action', $this->url('crud_imovel/passo3'));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form),
    $this->formCollection($form),
    $this->form()->closeTag();
    ?>
</section>