<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SIMOB '. $this->translate('Sistema Imobiliaria'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/notifIt.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.4.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/simob/admin.js')
            ->prependFile($this->basePath() . '/js/simob/default.js')
            ->prependFile($this->basePath() . '/js/libs/notifIt.js')
            ->prependFile($this->basePath() . '/js/libs/jquery-ui-1.10.4.custom.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php
        if(isset($this->mensagem)){
         echo $this->mensagem;
        }
        ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-superior">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#">Configurações</a></li>
                        <li class="active"><a href="#">Front-end</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <aside>
                <ul>
                   <li class='has-sub'><a href='#'><span>Imoveis</span></a>
                      <ul>
                         <li class='last'><a href='#'><span>Adicionar</span></a>
                         </li>
                         <li class='last'><a href='#'><span>Gerenciar</span></a>
                         </li>
                      </ul>
                   </li>
                   <li class='has-sub'><a href='#'><span>Localidades</span></a>
                       <ul>
                           <li class='has-sub'><a href='#'><span>Bairros</span></a>
                               <ul>
                                   <li class='last'><a href="<?php echo $this->url('crud_bairro/criarBairro');?>">Adicionar</a></li>
                                   <li class='last'><a href="<?php echo $this->url('crud_bairro/gerenciarBairro');?>">Gerenciar</a></li>
                               </ul>
                           </li>
                       </ul>
                   </li>
                   <li class='has-sub'><a href='#'><span>Comodos</span></a> <!-- comercial, residencial, etc -->
                       <ul>
                            <li class='last'><a href="#">Adicionar</a></li>
                            <li class='last'><a href="<?php echo $this->url('crud_comodo/index');?>">Gerenciar</a></li>
                       </ul>
                   </li>
                   <li class='has-sub'><a href='#'><span>Transações</span></a> <!-- venda, aluguel, etc -->
                       <ul>
                            <li class='last'><a href="#">Adicionar</a></li>
                            <li class='last'><a href="#">Gerenciar</a></li>
                       </ul>
                   </li>
                   <li class='has-sub'><a href='#'><span>Tipo de Uso(finalidade)</span></a> <!-- comercial, residencial, etc -->
                       <ul>
                            <li class='last'><a href="#">Adicionar</a></li>
                            <li class='last'><a href="#">Gerenciar</a></li>
                       </ul>
                   </li>
                   <li class='has-sub'><a href='#'><span>Clientes</span></a> <!-- comercial, residencial, etc -->
                       <ul>
                            <li class='last'><a href="#">Adicionar</a></li>
                            <li class='last'><a href="#">Gerenciar</a></li>
                       </ul>
                   </li>
                   
                </ul>
        </aside>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>simob - todos os direitos reservados</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>