<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SIMOB '. $this->translate('Sistema Imobiliaria'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/notifIt.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui-1.10.4.custom.min.css')
                        ->prependStylesheet($this->basePath() . '/css/top-menu.css')
                ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/simob/admin.js')
            ->prependFile($this->basePath() . '/js/simob/default.js')
            ->prependFile($this->basePath() . '/js/libs/notifIt.js')
            ->prependFile($this->basePath() . '/js/libs/jquery-ui-1.10.4.custom.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php
        if(isset($this->mensagemTopo)){
         echo $this->mensagemTopo;
        }
        if(isset($this->mensagemCentro)){
          echo $this->mensagemCentro;   
        }
        ?>
        <nav id="cssmenu">
            <ul>
                <li class="active"><a href="#">Configurações</a></li>
                <li class="active"><a href="<?php echo $this->url('rota_front_end')?>">Front-end</a></li>
            </ul>
        </nav>
        <aside>
            <a href="<?php echo $this->url('crud_imovel/passo1') ?>">
                <div class="menu-box">
                    <image src="/img/menu/criar-imovel.png"> 
                </div>
            </a>
            <a href="<?php echo $this->url('crud_imovel/index') ?>">
                <div class="menu-box">
                    <image src="/img/menu/gerenciar-imovel.png"> 
                </div>
            </a>
             <a href="<?php echo $this->url('crud_bairro/criarBairro') ?>">
                <div class="menu-box">
                    <image src="/img/menu/criar-bairro.png"> 
                </div>
            </a>
            <a href="<?php echo $this->url('crud_bairro/gerenciarBairro') ?>">
                <div class="menu-box">
                    <image src="/img/menu/gerenciar-bairro.png"> 
                </div>
            </a>
             <a href="<?php echo $this->url('crud_comodo/criar') ?>">
                <div class="menu-box">
                    <image src="/img/menu/criar-comodo.png"> 
                </div>
            </a>
            <a href="<?php echo $this->url('crud_comodo/index') ?>">
                <div class="menu-box">
                    <image src="/img/menu/gerenciar-comodo.png"> 
                </div>
            </a>
            <a href="<?php echo $this->url('crud_proprietario/criar') ?>">
                <div class="menu-box">
                    <image src="/img/menu/criar-proprietario.png"> 
                </div>
            </a>
            <a href="<?php echo $this->url('crud_proprietario/index') ?>">
                <div class="menu-box">
                    <image src="/img/menu/gerenciar-proprietario.png"> 
                </div>
            </a>
        </aside>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>simob - todos os direitos reservados</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>