  <tbody>       
    <?php foreach($this->proprietarios as $proprietario):?>
            <tr>
            <input type="hidden" class="id-proprietario" value="<?php echo $proprietario->getId();?>">
                <td class="nome">
                    <?php echo $proprietario->getNome();?>
                </td>
                <td class="CPF">
                    <?php echo $proprietario->mascaraCpf($proprietario->getCpf());?>
                </td>
                <?php
                    if($this->visao == "default"):                   
                ?>
                    <td>
                        <button class="alterar-proprietario update-default">Alterar</button>
                        <button class="deletar-proprietario delete-default">Deletar</button>
                    </td>
               <?php else:?>
                    <td>
                        <button class="selecionar-proprietario select-default">Selecionar</button>
                    </td>
               <?php endif;?>
            </tr>
    <?php endforeach;?>
    </tbody>