  <tbody>       
    <?php foreach($this->proprietarios as $proprietario):?>
            <tr>
            <input type="hidden" class="id-proprietario" value="<?php echo $proprietario->getId();?>">
                <td class="nome">
                    <?php echo $proprietario->getNome();?>
                </td>
                <td class="CPF">
                    <?php echo $proprietario->mascaraCpf($proprietario->getCpf());?>
                </td>
                <?php
                    if($this->url == "http://simob/proprietario/index"):
                ?>
                    <td>
                        <button class="alterar-proprietario">Alterar</button>
                        <button class="deletar-proprietario">Deletar</button>
                    </td>
               <?php elseif($this->url == "http://simob/imovel/passo2"):?>
                    <td>
                         <button class="selecionar-proprietario">Selecionar</button>
                    </td>
               <?php endif;?>
            </tr>
    <?php endforeach;?>
    </tbody>